export const GET_USERS = "GET_USERS";
export const GET_USERS_BY_NAME = "GET_USERS_BY_NAME";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";
export const GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL";

export const GET_STORES = "GET_STORES";
export const GET_STORES_BY_NAME = "GET_STORES_BY_NAME";
export const GET_STORE_BY_ID = "GET_STORE_BY_ID";

export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEWS_BY_RATING = "GET_REVIEWS_BY_RATING";
export const GET_REVIEWS_BY_WORD = "GET_REVIEWS_BY_WORD";
export const GET_REVIEWS_BY_ID = "GET_REVIEWS_BY_ID";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID";
export const GET_PRODUCTS_BY_ORDER = "GET_PRODUCTS_BY_ORDER";

export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITIES_BY_NAME = "GET_ACTIVITIES_BY_NAME";
export const GET_ACTIVITY_BY_ID = "GET_ACTIVITY_BY_ID";
export const GET_ACTIVITIES_BY_ORDER = "GET_ACTIVITIES_BY_ORDER";

